name: Build Python distributions and publish to PyPI

on:
  release:
    types:
      - published

jobs:
  pypi:
    name: Build and publish Python distributions to TestPyPI and PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build:prd

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --progress-bar off wheel twine cython
    - run: python setup.py sdist bdist_wheel
    - run: twine check dist/*

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
